// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createuserwithpassword.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (id, created_at, updated_at, name, password_hash)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
    RETURNING id, created_at, updated_at, name, password_hash
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	PasswordHash sql.NullString
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithPassword,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}
