// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createbookmark.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBookmark = `-- name: CreateBookmark :one
WITH inserted_bookmark AS (
    INSERT INTO post_bookmarks (id, created_at, updated_at, user_id, post_id)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, created_at, updated_at, user_id, post_id
)
SELECT inserted_bookmark.id, inserted_bookmark.created_at, inserted_bookmark.updated_at, inserted_bookmark.user_id, inserted_bookmark.post_id, posts.title AS post_title, posts.url AS post_url
FROM inserted_bookmark
INNER JOIN posts ON inserted_bookmark.post_id = posts.id
`

type CreateBookmarkParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

type CreateBookmarkRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
	PostTitle string
	PostUrl   string
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (CreateBookmarkRow, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
	)
	var i CreateBookmarkRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
		&i.PostTitle,
		&i.PostUrl,
	)
	return i, err
}
