// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createapikey.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, created_at, updated_at, key_hash, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, key_hash, user_id
`

type CreateAPIKeyParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	KeyHash   string
	UserID    uuid.UUID
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.KeyHash,
		arg.UserID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyHash,
		&i.UserID,
	)
	return i, err
}
