// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteapikeysforuser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAPIKeysForUser = `-- name: DeleteAPIKeysForUser :exec
DELETE FROM api_keys
WHERE user_id = $1
`

func (q *Queries) DeleteAPIKeysForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeysForUser, userID)
	return err
}
