// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletebookmark.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM post_bookmarks
WHERE user_id = $1 AND post_id = $2
`

type DeleteBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.UserID, arg.PostID)
	return err
}
