// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_posts_asc.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPostsForUserAsc = `-- name: GetPostsForUserAsc :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
where feed_follows.user_id = $1
order by posts.published_at asc
limit $2
`

type GetPostsForUserAscParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostsForUserAsc(ctx context.Context, arg GetPostsForUserAscParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserAsc, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
