// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getuserbyapikey.sql

package database

import (
	"context"
)

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
select users.id, users.created_at, users.updated_at, users.name, users.password_hash
from users
inner join api_keys on api_keys.user_id = users.id
where api_keys.key_hash = $1
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, keyHash string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, keyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}
