// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: searchposts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchPosts = `-- name: SearchPosts :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, similarity(lower(posts.title), lower($2)) as sim
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
where feed_follows.user_id = $1 and lower(posts.title) % lower($2)
order by sim desc
limit $3
`

type SearchPostsParams struct {
	UserID uuid.UUID
	Lower  string
	Limit  int32
}

type SearchPostsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
	Sim         float32
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPosts, arg.UserID, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
