// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setuserpassword.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at    = $3
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash sql.NullString
	UpdatedAt    time.Time
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
